language: ruby
rvm:
  - 2.3.0

env:
  global:
    - REPO_URI=git@github.com:love2d-community/love2d-book.git
    - REPO_IO_URI=git@github.com:love2d-book/love2d-book.github.io.git

bundler_args: --without production

script:
  - bundle exec ./render.sh

after_success:
  - ./deploy.sh
